// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/leadership/ExpertiseScorecard.tsx": () => import("../components/mockups/leadership/ExpertiseScorecard.tsx"),
  "./components/mockups/leadership/FlipReveal.tsx": () => import("../components/mockups/leadership/FlipReveal.tsx"),
  "./components/mockups/leadership/SpotlightStage.tsx": () => import("../components/mockups/leadership/SpotlightStage.tsx")
};
