import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Link } from "wouter";
import {
  ArrowLeft, ChevronDown, Sprout, Building2, Search,
  Leaf, Shield, DollarSign, Smartphone, Globe, Users,
  BarChart2, Lock, Handshake, Rocket, AlertTriangle, CheckCircle2
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

// ── Data ──────────────────────────────────────────────────────────────────────

type FAQ = { q: string; a: string | React.ReactNode; category: string };

const FARMER_FAQS: FAQ[] = [
  {
    category: "About Carbon Credits",
    q: "What are carbon credits?",
    a: "Carbon credits represent the removal or reduction of one metric ton of CO₂ (or equivalent greenhouse gases) from the atmosphere. Companies and individuals purchase them to offset their emissions and reduce their environmental impact.",
  },
  {
    category: "About Carbon Credits",
    q: "How do carbon credits work?",
    a: (
      <div className="space-y-3">
        <p>Carbon credits are generated by projects that remove or reduce emissions (e.g., planting trees). At SikaFields:</p>
        <ol className="list-decimal list-inside space-y-1.5 text-sm">
          <li>Farmers implement sustainable practices</li>
          <li>Carbon impact is measured and verified</li>
          <li>Credits are issued</li>
          <li>Buyers purchase credits to offset emissions</li>
          <li>Credits are retired permanently</li>
        </ol>
      </div>
    ),
  },
  {
    category: "About Carbon Credits",
    q: "How are carbon credits generated and verified?",
    a: (
      <div className="space-y-3">
        <p>Credits are generated through activities like reforestation or regenerative farming. SikaFields ensures accurate measurement using scientific models, monitoring and reporting (MRV), and third-party verification where applicable. This ensures credits are real, measurable, permanent, and additional.</p>
      </div>
    ),
  },
  {
    category: "About Carbon Credits",
    q: "What types of projects generate carbon credits on SikaFields?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Agroforestry</li>
        <li>Reforestation and afforestation</li>
        <li>Regenerative agriculture</li>
        <li>Soil carbon improvement</li>
        <li>Energy-efficient cookstoves</li>
      </ul>
    ),
  },
  {
    category: "About Carbon Credits",
    q: "Why are carbon credits important?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Help reduce global emissions</li>
        <li>Support sustainable farming</li>
        <li>Provide income to rural communities</li>
        <li>Enable companies to meet climate goals</li>
      </ul>
    ),
  },
  {
    category: "For Farmers & Landowners",
    q: "How do I join SikaFields as a farmer?",
    a: "You can register through the mobile app or work with a local field agent. You'll provide details about your land and farming practices. Our team will guide you through every step.",
  },
  {
    category: "For Farmers & Landowners",
    q: "What are the requirements to join?",
    a: (
      <div className="space-y-3">
        <p>To participate, farmers must:</p>
        <ul className="list-disc list-inside space-y-1.5 text-sm">
          <li>Be within the project zone</li>
          <li>Own or have rights to farmland (with witnesses if needed)</li>
          <li>Have minimum 1 hectare (2.5 acres)</li>
          <li>Be willing to plant or maintain trees (e.g., mahogany, neem, cassia)</li>
          <li>Ensure existing tree crops are not older than 5 years</li>
          <li>Follow environmental regulations</li>
          <li>Participate in training programs</li>
          <li>Commit to maintaining trees for at least 30 years</li>
          <li>Adopt sustainable practices (e.g., minimal tillage, low pesticide use)</li>
        </ul>
        <p className="text-sm font-medium text-primary mt-2">👉 This is strict by design — carbon markets depend on long-term credibility, not short-term participation.</p>
      </div>
    ),
  },
  {
    category: "For Farmers & Landowners",
    q: "Do I still own my land?",
    a: "Yes. You retain full ownership and control of your land at all times. SikaFields never acquires or encumbers your land.",
  },
  {
    category: "For Farmers & Landowners",
    q: "How do I earn money?",
    a: "You earn when your project is verified, carbon credits are issued, and credits are sold to buyers. You receive a direct share of the revenue after credits are sold.",
  },
  {
    category: "For Farmers & Landowners",
    q: "How and when do I get paid?",
    a: (
      <div className="space-y-2">
        <p>Payments are made after credits are sold via:</p>
        <ul className="list-disc list-inside space-y-1.5 text-sm">
          <li>Mobile money (e.g., MTN MoMo)</li>
          <li>Bank transfer</li>
          <li>Local payment systems</li>
        </ul>
        <p className="text-sm font-semibold text-amber-600 mt-2">⚠️ Important: Payments are not immediate — carbon verification takes time.</p>
      </div>
    ),
  },
  {
    category: "For Farmers & Landowners",
    q: "Do I need internet access?",
    a: "No. The SikaFields app supports offline data collection. You can record all your farming activities without connectivity and sync everything the next time you're in range.",
  },
  {
    category: "Trust, Verification & Integrity",
    q: "How does SikaFields ensure credibility?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>MRV (Monitoring, Reporting, Verification) framework</li>
        <li>Satellite and field data (where applicable)</li>
        <li>Internal validation systems</li>
        <li>Optional third-party verification</li>
      </ul>
    ),
  },
  {
    category: "Trust, Verification & Integrity",
    q: "How do you prevent fraud or double-counting?",
    a: "Each credit is uniquely recorded and retired after purchase. A full audit trail is maintained for every credit from issuance to retirement, making double-counting impossible.",
  },
  {
    category: "Trust, Verification & Integrity",
    q: "How long does it take to generate carbon credits?",
    a: (
      <div className="space-y-2 text-sm">
        <p>Carbon credits are not instant. Depending on the project:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Initial estimates: weeks</li>
          <li>Verification & issuance: months to years</li>
        </ul>
        <p className="font-medium text-primary mt-1">👉 This is essential to ensure real climate impact, not inflated claims.</p>
      </div>
    ),
  },
  {
    category: "Security & Platform",
    q: "Is my data secure?",
    a: "Yes. SikaFields uses encrypted storage, secure cloud infrastructure, and role-based access controls to protect all farmer data.",
  },
  {
    category: "Security & Platform",
    q: "Is SikaFields free to use?",
    a: "Registration is free. A small commission is charged only when credits are sold — so you pay nothing upfront.",
  },
  {
    category: "Partnerships",
    q: "How can I partner with SikaFields?",
    a: (
      <div className="space-y-2 text-sm">
        <p>You can collaborate as:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Corporate sponsor</li>
          <li>NGO or development partner</li>
          <li>Government agency</li>
          <li>Technology or research partner</li>
        </ul>
        <p className="mt-2">Contact us at <a href="mailto:info@sikafield.net" className="text-primary hover:underline">info@sikafield.net</a> to explore partnership opportunities.</p>
      </div>
    ),
  },
  {
    category: "Critical Transparency",
    q: "Are carbon credits guaranteed income?",
    a: (
      <div className="space-y-2 text-sm">
        <p className="font-semibold text-foreground">No.</p>
        <p>Carbon income depends on:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Project performance</li>
          <li>Verification success</li>
          <li>Market demand</li>
        </ul>
        <p className="text-amber-600 font-medium mt-2">⚠️ We believe in full transparency. Carbon income is a genuine opportunity, not a guarantee.</p>
      </div>
    ),
  },
];

const BUYER_FAQS: FAQ[] = [
  {
    category: "Overview",
    q: "What is SikaFields?",
    a: "SikaFields is a climate technology platform that enables organizations to invest in high-quality, nature-based carbon removal projects while delivering measurable environmental and social impact in emerging markets.",
  },
  {
    category: "Overview",
    q: "What problem does SikaFields solve?",
    a: (
      <div className="space-y-2 text-sm">
        <p>Many carbon offset solutions lack transparency, traceability, and real community impact. SikaFields addresses this by connecting buyers directly to verified, farmer-led projects — ensuring credible carbon removal and measurable ESG outcomes.</p>
      </div>
    ),
  },
  {
    category: "Carbon Credits & ESG",
    q: "What types of carbon credits does SikaFields offer?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Agroforestry</li>
        <li>Reforestation and afforestation</li>
        <li>Regenerative agriculture</li>
        <li>Soil carbon sequestration</li>
        <li>Energy-efficient cookstoves (energy transition projects)</li>
      </ul>
    ),
  },
  {
    category: "Carbon Credits & ESG",
    q: "How do SikaFields credits align with ESG frameworks?",
    a: (
      <div className="space-y-2 text-sm">
        <p>SikaFields supports all three ESG pillars:</p>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Environmental (E):</strong> Verified CO₂ removal and biodiversity restoration</li>
          <li><strong>Social (S):</strong> Increased farmer income, job creation, community development</li>
          <li><strong>Governance (G):</strong> Transparent MRV processes, audit trails, and reporting</li>
        </ul>
      </div>
    ),
  },
  {
    category: "Carbon Credits & ESG",
    q: "Can SikaFields credits support net-zero commitments?",
    a: "Yes. Our credits are suitable for voluntary carbon offsetting, Scope 3 emissions reduction strategies, and net-zero transition plans — as a complementary measure alongside direct emissions reductions.",
  },
  {
    category: "Verification, Quality & Risk",
    q: "How are carbon credits verified?",
    a: (
      <div className="space-y-2 text-sm">
        <p>SikaFields applies a rigorous MRV (Monitoring, Reporting, Verification) framework including:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Scientific carbon estimation models</li>
          <li>Field data collection and validation</li>
          <li>Remote sensing (where applicable)</li>
          <li>Independent third-party verification (where required)</li>
        </ul>
      </div>
    ),
  },
  {
    category: "Verification, Quality & Risk",
    q: "How do you ensure credit quality?",
    a: (
      <div className="space-y-2 text-sm">
        <p>All credits meet key integrity principles:</p>
        <ul className="list-disc list-inside space-y-1">
          <li><strong>Additionality:</strong> Projects would not occur without carbon financing</li>
          <li><strong>Permanence:</strong> Long-term carbon storage (e.g., 30-year commitments)</li>
          <li><strong>No double-counting:</strong> Unique registry and retirement system</li>
          <li><strong>Leakage control:</strong> Monitoring to prevent emissions shifting elsewhere</li>
        </ul>
      </div>
    ),
  },
  {
    category: "Verification, Quality & Risk",
    q: "What risks should buyers be aware of?",
    a: (
      <div className="space-y-2 text-sm">
        <p>Like all nature-based solutions, carbon sequestration takes time, environmental risks (drought, fire) may impact outcomes, and verification timelines can be long. SikaFields mitigates these through conservative estimation models, ongoing monitoring, and diversified project portfolios.</p>
      </div>
    ),
  },
  {
    category: "Pricing & Commercial",
    q: "How is pricing determined?",
    a: "Pricing is based on project type and methodology, geographic location, verification level, and market demand. Nature-based credits often carry premium value due to co-benefits (biodiversity, community income). SikaFields ensures transparent pricing for all listings.",
  },
  {
    category: "Pricing & Commercial",
    q: "Are long-term purchase agreements available?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Forward contracts</li>
        <li>Multi-year offtake agreements</li>
        <li>Custom corporate sustainability partnerships</li>
      </ul>
    ),
  },
  {
    category: "Pricing & Commercial",
    q: "What payment options are available?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Bank transfers</li>
        <li>Corporate invoicing</li>
        <li>Secure digital payments</li>
      </ul>
    ),
  },
  {
    category: "Impact & Reporting",
    q: "What reporting do buyers receive?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Carbon offset certificates (upon retirement)</li>
        <li>Project-level data (location, methodology)</li>
        <li>ESG impact reports</li>
        <li>Community impact metrics (farmer income, trees planted)</li>
      </ul>
    ),
  },
  {
    category: "Impact & Reporting",
    q: "Can we integrate this into our ESG reporting?",
    a: "Yes. Our reporting is structured to support sustainability reports, ESG disclosures, and corporate responsibility reporting — ready to drop into your annual report.",
  },
  {
    category: "Impact & Reporting",
    q: "Can we track impact in real time?",
    a: "Yes. The SikaFields dashboard provides CO₂ offset tracking, portfolio-level insights, and project performance updates.",
  },
  {
    category: "Social Impact",
    q: "What makes SikaFields different from other carbon platforms?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Direct engagement with smallholder farmers</li>
        <li>Focus on Africa and emerging markets</li>
        <li>Strong social impact co-benefits</li>
        <li>Transparent, data-driven credit lifecycle</li>
      </ul>
    ),
  },
  {
    category: "Social Impact",
    q: "What social impact do these projects deliver?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Increased farmer income</li>
        <li>Job creation in rural communities</li>
        <li>Food security improvements</li>
        <li>Gender and youth inclusion</li>
      </ul>
    ),
  },
  {
    category: "Governance & Compliance",
    q: "How does SikaFields ensure governance and transparency?",
    a: "We maintain a centralized registry with audit trails, clear credit lifecycle tracking (issuance → sale → retirement), and data integrity controls with access management.",
  },
  {
    category: "Governance & Compliance",
    q: "Are credits retired after purchase?",
    a: "Yes. All purchased credits are retired immediately or on request, ensuring they cannot be reused or resold. You receive a permanent certificate of offset.",
  },
  {
    category: "Enterprise & Partnerships",
    q: "Can SikaFields support enterprise-scale programs?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Custom project development</li>
        <li>White-labeled sustainability programs</li>
        <li>Regional or sector-specific carbon portfolios</li>
      </ul>
    ),
  },
  {
    category: "Enterprise & Partnerships",
    q: "Can we co-develop projects with SikaFields?",
    a: "Yes. We partner with organizations to design tailored carbon projects, align with corporate sustainability goals, and deliver long-term ESG impact. Contact us at info@sikafield.net.",
  },
  {
    category: "Critical Transparency",
    q: "Are carbon credits a substitute for emission reductions?",
    a: (
      <div className="space-y-2 text-sm">
        <p className="font-semibold text-foreground">No.</p>
        <p>Carbon credits should complement emissions reduction strategies and offset unavoidable emissions — not replace direct reductions.</p>
        <p className="text-amber-600 font-medium">👉 Over-reliance on offsets without reduction exposes companies to reputational and regulatory risk.</p>
      </div>
    ),
  },
  {
    category: "Critical Transparency",
    q: "What is the timeline for impact realization?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li><strong>Short-term:</strong> Project onboarding and initial estimates</li>
        <li><strong>Medium-term:</strong> Verification and issuance (months to years)</li>
        <li><strong>Long-term:</strong> Sustained carbon removal and community benefits</li>
      </ul>
    ),
  },
  {
    category: "Future Outlook",
    q: "How is SikaFields evolving?",
    a: (
      <ul className="list-disc list-inside space-y-1.5 text-sm">
        <li>Advanced MRV technologies (AI + satellite data)</li>
        <li>Scalable project pipelines across Africa</li>
        <li>Enhanced transparency layers (potential blockchain integration)</li>
      </ul>
    ),
  },
];

// ── Category icon map ─────────────────────────────────────────────────────────
const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  "About Carbon Credits": <Leaf className="w-3.5 h-3.5" />,
  "For Farmers & Landowners": <Sprout className="w-3.5 h-3.5" />,
  "Trust, Verification & Integrity": <Shield className="w-3.5 h-3.5" />,
  "Security & Platform": <Lock className="w-3.5 h-3.5" />,
  "Partnerships": <Handshake className="w-3.5 h-3.5" />,
  "Critical Transparency": <AlertTriangle className="w-3.5 h-3.5" />,
  "Overview": <Building2 className="w-3.5 h-3.5" />,
  "Carbon Credits & ESG": <BarChart2 className="w-3.5 h-3.5" />,
  "Verification, Quality & Risk": <Shield className="w-3.5 h-3.5" />,
  "Pricing & Commercial": <DollarSign className="w-3.5 h-3.5" />,
  "Impact & Reporting": <BarChart2 className="w-3.5 h-3.5" />,
  "Social Impact": <Users className="w-3.5 h-3.5" />,
  "Governance & Compliance": <Lock className="w-3.5 h-3.5" />,
  "Enterprise & Partnerships": <Handshake className="w-3.5 h-3.5" />,
  "Future Outlook": <Rocket className="w-3.5 h-3.5" />,
};

// ── Components ────────────────────────────────────────────────────────────────

function AccordionItem({ faq, index }: { faq: FAQ; index: number }) {
  const [open, setOpen] = useState(false);
  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: index * 0.04, ease: [0.22, 1, 0.36, 1] }}
      className={cn(
        "border border-border rounded-2xl overflow-hidden transition-colors duration-200",
        open ? "bg-primary/3 border-primary/30 shadow-sm shadow-primary/10" : "bg-card hover:bg-muted/40"
      )}
    >
      <button
        className="w-full flex items-start gap-4 px-6 py-5 text-left"
        onClick={() => setOpen(o => !o)}
      >
        <span className={cn(
          "mt-0.5 w-6 h-6 rounded-lg flex items-center justify-center shrink-0 transition-colors",
          open ? "bg-primary text-white" : "bg-muted text-muted-foreground"
        )}>
          <CheckCircle2 className="w-3.5 h-3.5" />
        </span>
        <span className="flex-1 font-semibold text-foreground text-base leading-snug">{faq.q}</span>
        <motion.span
          animate={{ rotate: open ? 180 : 0 }}
          transition={{ duration: 0.25 }}
          className="shrink-0 mt-0.5 text-muted-foreground"
        >
          <ChevronDown className="w-5 h-5" />
        </motion.span>
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
            className="overflow-hidden"
          >
            <div className="px-6 pb-5 pt-0 ml-10 text-muted-foreground text-sm leading-relaxed">
              {typeof faq.a === "string" ? <p>{faq.a}</p> : faq.a}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

function FAQGroup({ faqs, search }: { faqs: FAQ[]; search: string }) {
  const filtered = search.trim()
    ? faqs.filter(f => f.q.toLowerCase().includes(search.toLowerCase()) || (typeof f.a === "string" && f.a.toLowerCase().includes(search.toLowerCase())))
    : faqs;

  const grouped = filtered.reduce<Record<string, FAQ[]>>((acc, faq) => {
    if (!acc[faq.category]) acc[faq.category] = [];
    acc[faq.category].push(faq);
    return acc;
  }, {});

  if (filtered.length === 0) {
    return (
      <div className="text-center py-20">
        <Search className="w-10 h-10 text-muted-foreground/40 mx-auto mb-3" />
        <p className="text-muted-foreground">No results found for "<span className="font-semibold text-foreground">{search}</span>"</p>
      </div>
    );
  }

  let itemIndex = 0;
  return (
    <div className="space-y-10">
      {Object.entries(grouped).map(([category, items]) => (
        <div key={category}>
          <div className="flex items-center gap-2 mb-4">
            <span className="w-6 h-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
              {CATEGORY_ICONS[category] ?? <Leaf className="w-3.5 h-3.5" />}
            </span>
            <h3 className="text-sm font-bold uppercase tracking-widest text-muted-foreground">{category}</h3>
          </div>
          <div className="space-y-2">
            {items.map(faq => (
              <AccordionItem key={faq.q} faq={faq} index={itemIndex++} />
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function FAQPage() {
  const initialTab = (): "farmers" | "buyers" => {
    if (typeof window !== "undefined") {
      const params = new URLSearchParams(window.location.search);
      const t = params.get("tab");
      if (t === "buyers") return "buyers";
    }
    return "farmers";
  };
  const [tab, setTab] = useState<"farmers" | "buyers">(initialTab);
  const [search, setSearch] = useState("");

  const tabs = [
    { key: "farmers" as const, label: "For Farmers", icon: <Sprout className="w-4 h-4" />, count: FARMER_FAQS.length, color: "text-primary" },
    { key: "buyers" as const, label: "For Corporate Buyers", icon: <Building2 className="w-4 h-4" />, count: BUYER_FAQS.length, color: "text-accent" },
  ];

  const activeFaqs = tab === "farmers" ? FARMER_FAQS : BUYER_FAQS;

  return (
    <div className="min-h-screen bg-background text-foreground font-body">

      {/* ── Navbar ── */}
      <header className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border/60 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <img src="/sikafields-logo-new.png" alt="SikaFields" className="h-9 w-auto" />
          </Link>
          <Link href="/" className="flex items-center gap-1.5 text-sm font-medium text-muted-foreground hover:text-primary transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </div>
      </header>

      {/* ── Hero ── */}
      <section className="relative overflow-hidden bg-gradient-to-br from-[hsl(160_28%_6%)] via-[hsl(150_22%_10%)] to-[hsl(145_28%_14%)] py-20 px-4">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-[-30%] left-[-10%] w-[600px] h-[600px] rounded-full bg-primary/20 blur-[120px]" />
          <div className="absolute bottom-[-20%] right-[-5%] w-[500px] h-[500px] rounded-full bg-accent/15 blur-[110px]" />
        </div>
        <div className="relative max-w-4xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <span className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-primary/30 bg-primary/10 text-primary text-xs font-semibold uppercase tracking-widest mb-6">
              <Leaf className="w-3.5 h-3.5" /> Frequently Asked Questions
            </span>
          </motion.div>
          <motion.h1
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.1 }}
            className="text-4xl sm:text-5xl lg:text-6xl font-display font-black text-white leading-tight mb-4"
          >
            Got questions?<br /><span className="text-primary">We've got answers.</span>
          </motion.h1>
          <motion.p
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.2 }}
            className="text-white/60 text-lg max-w-xl mx-auto mb-8"
          >
            Everything you need to know about carbon credits, farmer participation, and corporate purchases — in one place.
          </motion.p>

          {/* Search bar */}
          <motion.div
            initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.3 }}
            className="relative max-w-lg mx-auto"
          >
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-white/30" />
            <input
              type="text"
              placeholder="Search questions…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full pl-12 pr-5 py-4 rounded-2xl bg-white/10 border border-white/15 text-white placeholder:text-white/30 focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary/50 transition-all text-sm backdrop-blur-sm"
            />
          </motion.div>
        </div>
      </section>

      {/* ── Main content ── */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">

        {/* Tab switcher */}
        <div className="flex gap-3 mb-10 p-1.5 bg-muted rounded-2xl">
          {tabs.map(t => (
            <button
              key={t.key}
              onClick={() => { setTab(t.key); setSearch(""); }}
              className={cn(
                "flex-1 flex items-center justify-center gap-2 px-5 py-3 rounded-xl font-semibold text-sm transition-all duration-200",
                tab === t.key
                  ? "bg-background text-foreground shadow-sm shadow-black/8"
                  : "text-muted-foreground hover:text-foreground"
              )}
            >
              <span className={tab === t.key ? t.color : ""}>{t.icon}</span>
              <span>{t.label}</span>
              <span className={cn(
                "px-2 py-0.5 rounded-full text-xs font-bold",
                tab === t.key ? "bg-primary/10 text-primary" : "bg-muted-foreground/15 text-muted-foreground"
              )}>
                {t.count}
              </span>
            </button>
          ))}
        </div>

        {/* FAQ list */}
        <AnimatePresence mode="wait">
          <motion.div
            key={tab}
            initial={{ opacity: 0, x: tab === "farmers" ? -20 : 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: tab === "farmers" ? 20 : -20 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
          >
            <FAQGroup faqs={activeFaqs} search={search} />
          </motion.div>
        </AnimatePresence>

        {/* Bottom CTA */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-16 rounded-3xl bg-gradient-to-br from-primary/10 to-accent/5 border border-primary/20 p-10 text-center"
        >
          <div className="w-14 h-14 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-5">
            <Handshake className="w-7 h-7 text-primary" />
          </div>
          <h3 className="text-2xl font-display font-bold text-foreground mb-2">Still have questions?</h3>
          <p className="text-muted-foreground mb-6 max-w-sm mx-auto text-sm">
            Our team is happy to help. Reach out and we'll get back to you within 3–5 business days.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 justify-center">
            <Link href="/#contact">
              <Button size="lg" className="font-bold bg-primary hover:bg-primary/90 shadow-lg shadow-primary/25 rounded-2xl">
                Contact Us
              </Button>
            </Link>
            <a
              href="mailto:info@sikafield.net"
              className="inline-flex items-center justify-center px-6 py-3 rounded-2xl border border-border text-foreground font-semibold text-sm hover:bg-muted transition-colors"
            >
              info@sikafield.net
            </a>
          </div>
        </motion.div>
      </div>

      {/* ── Footer strip ── */}
      <footer className="border-t border-border bg-muted/30 py-8 px-4 text-center mt-8">
        <p className="text-sm text-muted-foreground">
          © {new Date().getFullYear()} SikaFields. All rights reserved. &nbsp;·&nbsp;
          <a href="mailto:info@sikafield.net" className="hover:text-primary transition-colors">info@sikafield.net</a>
        </p>
      </footer>
    </div>
  );
}
